server:
  port: 8080  # API Gateway będzie działać na porcie 8080

spring:
  application:
    name: api-gateway  # Nazwa mikroserwisu dla Eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Automatyczne wykrywanie mikroserwisów z Eureka
          lower-case-service-id: true  # ID usług w małych literach
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Adres serwera Eureka
jwt:
  secret: 6b43b0d74f72be3e021f3a56a1a345f84f2c4d